# =======================
#  Global site settings
# =======================
title: "Portfolio"
description: "Senior Software Engineer | AI & NLP in Healthcare"
url: "https://palasht75.github.io"   # production URL
baseurl: ""                          # user-site root

# Theme (GitHub Pages remote copy of Minimal-Mistakes)
remote_theme: "mmistakes/minimal-mistakes"
# theme: "minimal-mistakes-jekyll"

# Plugins (all are whitelisted for GitHub Pages)
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# -----------------------
#  Author & social links
# -----------------------
author:
  name: "Palash"
  avatar: "/assets/images/avatar.jpg"
  bio: "Incoming M.Eng @ uOttawa • AI-driven healthcare engineer"
  location: "Nagpur, Maharashtra, India"
  email: "palasht75@gmail.com"

social:
  github:   "palasht75"
  linkedin: "palasht75"
  email:    "palasht75@gmail.com"
  rss:      true

# -----------------------
#  Header navigation
# -----------------------
header_pages:
  - about.md
  - projects/index.md
  - media/index.md
  - contact.md

# -----------------------
#  Pagination (blog only)
# -----------------------
paginate: 5
paginate_path: "/blog/page:num/"

# -----------------------
#  Default front-matter
# -----------------------
defaults:
  - scope:
      path: "projects"
    values:
      layout: single
  - scope:
      path: "media"
    values:
      layout: single
